server:
  port: 8889
spring:
  application:
    name: configserver
  cloud:
    bus:
      trace:
       enable: true
    config:
      server:
        git:
          uri: https://github.com/Dongge-666-Boop/lzd.git #git仓库地址
          searchPaths: config #仓库路径cls
          username: Dongge-666-Boop #git仓库用户名
          password: lzd13712917183 #git仓库密码
      label: master #仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/