server:
  port: 8040
spring:
  application:
    name: order
  datasource:
    name: ordering_meals
    url: jdbc:mysql://localhost:3306/ordering_mealsse?Unicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: lzd13712917183
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.southwind.entity